### Status Request
GET {{host}}:{{port}}

### Send POST to export data
POST {{host}}:{{port}}/excel-export
Content-Type: application/json

{
  "db": {
    "host": "{{db_host}}",
    "port": "{{db_port}}",
    "name": "{{db_name}}",
    "user": "{{db_user}}",
    "password": "{{db_password}}"
  },
  "sql": "select * from country",
  "fields": [
    {
      "name": "Name",
      "type": "string",
      "label": "Название"
    },
    {
      "name": "Code",
      "type": "string",
      "label": "Код"
    }
  ]
}

### Send POST to export data with filters
POST {{host}}:{{port}}/excel-export
Content-Type: application/json

{
  "db": {
    "host": "{{db_host}}",
    "port": "{{db_port}}",
    "name": "{{db_name}}",
    "user": "{{db_user}}",
    "password": "{{db_password}}"
  },
  "sql": "select * from country where Region = 'Southern Europe'",
  "fields": [
    {
      "name": "Name",
      "type": "string",
      "label": "Название"
    },
    {
      "name": "Code",
      "type": "string",
      "label": "Код"
    }
  ],
  "filters": [
    {
      "label": "Регион",
      "value": "Southern Europe"
    }
  ]
}